development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:76487f9c7eb4861f3abe025d9908eb1a@angelfish.redistogo.com:9932/
  channel_prefix: one-voice-fresh-start_production
