
development:
  adapter: postgresql
  encoding: unicode
  database: one_voice_development_1
  pool: 5
  username: postgres
  password: bitmaker
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: one_voice_test_1
  pool: 5
  username: postgres
  password: bitmaker
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: one_voice_production_1
  pool: 5
  username: postgres
  password:
